export default [
  {
    id: 1,
    sender: "Mark Weber",
    action: "reacted to your recent post",
    post: "My first tournament today!",
    duration: "1m ago",
    seen: false,
    image: "/images/avatar-mark-webber.webp",
  },
  {
    id: 2,
    sender: "Angela Gray",
    action: "followed you",
    post: "",
    duration: "5m ago",
    seen: false,
    image: "/images/avatar-angela-gray.webp",
  },
  {
    id: 3,
    sender: "Jacob Thompson",
    action: "has joined your group",
    post: "Chess Club",
    duration: "1 day ago",
    seen: false,
    image: "/images/avatar-jacob-thompson.webp",
  },
  {
    id: 4,
    sender: "Rizky Hasanuddin",
    action: "sent you a private message",
    post: "",
    duration: "1m ago",
    seen: true,
    image: "/images/avatar-rizky-hasanuddin.webp",
  },
  {
    id: 5,
    sender: "Kimberly Smith",
    action: "commented on your picture",
    post: "",
    duration: " 1 week ago",
    seen: true,
    image: "/images/avatar-kimberly-smith.webp",
  },
  {
    id: 6,
    sender: "Nathan Peterson",
    action: "reacted to your recent post",
    post: "5 end-game strategies to increase your win rate",
    duration: "2 weeks ago",
    seen: true,
    image: "/images/avatar-nathan-peterson.webp",
  },
  {
    id: 7,
    sender: "Anna Kim",
    action: "left the group",
    post: "Chess Club",
    duration: "2 weeks ago",
    seen: true,
    image: "/images/avatar-anna-kim.webp",
  },
];
